### ISSUE TITLE
Problem with /reload

### ISSUE THREAD

**Issue by G00golplexian** [MrCaira/WowheadLink_Grabber#1]
After you /reload the hotkey ctrl+c just triggers the character preview. seems like its not initialized properly after reloading. Once you relog again, its initialized.

PS: Very nice addon, quite simple but powerful!

Greetings,
G00

**Comment by fubaBfA** [comment]
seems this error was temporary while i dont played  
means it now works for classic (1.13.2) and retail (8.2.5) for me!
